export { default as About } from "./About";
export { default as Cart } from "./Cart";
export { default as Checkout } from "./Checkout";
export { default as Error } from "./Error";
export { default as HomeLayout } from "./HomeLayout";
export { Landing, landingLoader } from "./landing";
export { SingleProduct, productLoader } from "./singleProduct";
export { default as Login } from "./Login";
export { default as Orders } from "./Orders";
export { Products, productsLoader } from "./products";
export { default as Register } from "./Register";
